//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int Id_adresu { get; set; }
        public string Numer_zamowienia { get; set; }
        public string Miejscowosc { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu { get; set; }
    }
}
